services:
  redis:
    image: redis:7-alpine
    container_name: vsuet_rating_v2-redis
    command: ["redis-server", "--save", "60", "1", "--dbfilename", "dump.rdb", "--dir", "/data"]
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data

  app:
    build: .
    container_name: vsuet_rating_v2-fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    container_name: vsuet_rating_v2-nginx
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  redis-dev-data:
